stages:
- prepare
- build
- analyse
- deploy
- build-derived

variables:
  DOCKER_DRIVER: overlay2 # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374, https://docs.docker.com/storage/storagedriver/overlayfs-driver/
  DOCKER_TLS_CERTDIR: "" # Work around failing CI jobs: see https://gitlab.com/gitlab-org/gitlab-ce/issues/64959#note_194582424

.docker-build-base: &docker-build-base
  stage: build
  tags:
  - docker
  image: docker:git
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_JOB_NAME}:${CI_COMMIT_REF_NAME}
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f ${CI_JOB_NAME} -t ${CONTAINER_IMAGE} .
  - docker push ${CONTAINER_IMAGE}

build-ubuntu-1804:
  <<: *docker-build-base

build-ubuntu-2004:
  <<: *docker-build-base

.build-ubuntu-rolling:
  <<: *docker-build-base

.build-python:
  <<: *docker-build-base

build-ubuntu-templight:
  <<: *docker-build-base
  stage: build-derived
  when: manual

test-images:
  stage: analyse
  tags:
  - docker
  image: endeveit/docker-jq
  script:
  - ./run-pipeline.sh

deploy-images:
  stage: deploy
  only:
  - master
  tags:
  - docker
  image: docker:git
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:${CI_COMMIT_REF_NAME}
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:${CI_COMMIT_REF_NAME}
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-2004:${CI_COMMIT_REF_NAME}
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-rolling:${CI_COMMIT_REF_NAME}
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:latest
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:latest
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-2004:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-2004:latest
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-rolling:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-rolling:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-2004:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-rolling:latest
