stages:
- prepare
- build
- analyse
- deploy
- build-derived

.docker-build-base: &docker-build-base
  stage: build
  tags:
  - docker
  image: docker:git
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_JOB_NAME}:${CI_COMMIT_REF_NAME}
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f ${CI_JOB_NAME} -t ${CONTAINER_IMAGE} .
  - docker push ${CONTAINER_IMAGE}

arch:
  <<: *docker-build-base
  stage: prepare
  before_script:
  - wget http://ftp.nluug.nl/os/Linux/distr/archlinux/iso/`date +%Y.%m`.01/archlinux-bootstrap-`date +%Y.%m`.01-x86_64.tar.gz
  - tar -xzpf archlinux-bootstrap-`date +%Y.%m`.01-x86_64.tar.gz
  - (cd root.x86_64/; tar -cjpf ../archlinux.tar.bz2 .)

build-arch:
  <<: *docker-build-base

build-ubuntu-1804:
  <<: *docker-build-base

build-ubuntu-rolling:
  <<: *docker-build-base

build-ubuntu-templight:
  <<: *docker-build-base
  stage: build-derived
  when: manual

build-compose:
  <<: *docker-build-base

build-doxygen:
  <<: *docker-build-base

test-images:
  stage: analyse
  tags:
  - docker
  image: endeveit/docker-jq
  script:
  - ./run-pipeline.sh

deploy-images:
  stage: deploy
  only:
  - master
  tags:
  - docker
  image: docker:git
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:${CI_COMMIT_REF_NAME}
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:${CI_COMMIT_REF_NAME}
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-compose:${CI_COMMIT_REF_NAME}
  - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-doxygen:${CI_COMMIT_REF_NAME}
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:latest
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:latest
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-compose:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-compose:latest
  - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-doxygen:${CI_COMMIT_REF_NAME} ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-doxygen:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-arch:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-ubuntu-1804:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-compose:latest
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/build-doxygen:latest