stages:
- prepare
- build

.docker-build-base: &docker-build-base
  stage: build
  tags:
  - docker
  image: docker:git
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_JOB_NAME}:${CI_BUILD_REF_NAME}
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f ${CI_JOB_NAME} -t ${CONTAINER_IMAGE} .
  - docker push ${CONTAINER_IMAGE}

arch:
  <<: *docker-build-base
  stage: prepare
  script:
  - wget http://ftp.nluug.nl/os/Linux/distr/archlinux/iso/`date +%Y.%m`.01/archlinux-bootstrap-`date +%Y.%m`.01-x86_64.tar.gz
  - tar -xzpf archlinux-bootstrap-`date +%Y.%m`.01-x86_64.tar.gz
  - (cd root.x86_64/; tar -cjpf ../archlinux.tar.bz2 .)
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f ${CI_JOB_NAME} -t ${CONTAINER_IMAGE} .
  - docker push ${CONTAINER_IMAGE}

build-arch:
  <<: *docker-build-base

build-ubuntu:
  <<: *docker-build-base

build-compose:
  <<: *docker-build-base
