stages:
- prepare
- build
- analyse
- deploy
- build-derived

variables:
  DOCKER_DRIVER: overlay2 # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374, https://docs.docker.com/storage/storagedriver/overlayfs-driver/
  DOCKER_TLS_CERTDIR: "" # Work around failing CI jobs: see https://gitlab.com/gitlab-org/gitlab-ce/issues/64959#note_194582424
  PROJECT_REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  IMAGE_TAG: ${CI_COMMIT_SHA}
  IMAGE_TAG_TEST: ${CI_COMMIT_SHA}-test

.docker-build-base: &docker-build-base
  stage: build
  tags:
  - docker
  image: docker:git
  variables:
    CONTAINER_IMAGE: ${PROJECT_REGISTRY}/${CI_JOB_NAME}:${IMAGE_TAG_TEST}
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f ${CI_JOB_NAME} -t ${CONTAINER_IMAGE} .
  - echo "Pushing image as ${CONTAINER_IMAGE}"
  - docker push ${CONTAINER_IMAGE}

build-ubuntu-2004:
  <<: *docker-build-base

build-ubuntu-2204:
  <<: *docker-build-base

build-ubuntu-rolling:
  <<: *docker-build-base

build-python:
  <<: *docker-build-base

build-flatpak:
  <<: *docker-build-base

build-ubuntu-templight:
  <<: *docker-build-base
  stage: build-derived
  when: manual

test-images:
  stage: analyse
  tags:
  - docker
  image: endeveit/docker-jq
  script:
  - ./run-pipeline.sh ${IMAGE_TAG_TEST}

deploy-images:
  stage: deploy
  tags:
  - docker
  image: docker:git
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - |
    for image in build-ubuntu-2004 build-ubuntu-2204 build-ubuntu-rolling build-python build-flatpak; do
      docker buildx imagetools create --tag ${PROJECT_REGISTRY}/$image:${IMAGE_TAG} ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST}
      docker rmi ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST}
    done
