stages:
  - build
  - analyze
  - deploy
  - build-derived

variables:
  DOCKER_DRIVER: overlay2 # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374, https://docs.docker.com/storage/storagedriver/overlayfs-driver/
  DOCKER_TLS_CERTDIR: "" # Work around failing CI jobs: see https://gitlab.com/gitlab-org/gitlab-ce/issues/64959#note_194582424
  PROJECT_REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  IMAGE_TAG: sha-${CI_COMMIT_SHA}
  IMAGE_TAG_TEST: sha-test-${CI_COMMIT_SHA}
  DEPLOY_IMAGES: >-
    builder-ubuntu-2204
    builder-ubuntu-rolling
    builder-flatpak
    runtime-ubuntu-2204

.docker-build-base:
  stage: build
  tags:
    - docker
  image: docker:git
  variables:
    CONTAINER_IMAGE: ${PROJECT_REGISTRY}/${IMAGE_KIND}-${IMAGE_NAME}:${IMAGE_TAG_TEST}
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - echo "Pushing image as ${CONTAINER_IMAGE}"
    - >
      docker buildx build
      --push
      --annotation "org.opencontainers.image.title=${CI_COMMIT_TITLE} [${CI_COMMIT_REF_NAME} ${CI_COMMIT_SHORT_SHA}]"
      --file ./${IMAGE_KIND}/${IMAGE_NAME}.Dockerfile
      --tag ${CONTAINER_IMAGE}
      ./${IMAGE_KIND}/


builder/ubuntu-2204:
  extends: .docker-build-base
  variables:
    IMAGE_KIND: builder
    IMAGE_NAME: ubuntu-2204

builder/ubuntu-rolling:
  extends: .docker-build-base
  variables:
    IMAGE_KIND: builder
    IMAGE_NAME: ubuntu-rolling

builder/flatpak:
  extends: .docker-build-base
  variables:
    IMAGE_KIND: builder
    IMAGE_NAME: flatpak

builder/ubuntu-templight:
  extends: .docker-build-base
  stage: build-derived
  when: manual
  variables:
    IMAGE_KIND: builder
    IMAGE_NAME: ubuntu-templight


runtime/ubuntu-2204:
  extends: .docker-build-base
  variables:
    IMAGE_KIND: runtime
    IMAGE_NAME: ubuntu-2204


test-images:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE != "push"
  tags:
    - docker
  image: endeveit/docker-jq
  script:
    - ./run-pipeline.sh ${IMAGE_TAG_TEST}

# Use crane for efficient remote retagging
deploy-images:
  stage: deploy
  tags:
    - docker
  # See https://github.com/google/go-containerregistry/tree/main/cmd/crane#using-with-gitlab
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: ['']
  script:
    - crane auth login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      for image in ${DEPLOY_IMAGES}; do
        crane tag ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST} ${IMAGE_TAG}
        crane delete ${PROJECT_REGISTRY}/$image:${IMAGE_TAG_TEST}
      done
