FROM gitlabregistry.pep.cs.ru.nl/pep/docker-build/arch

RUN pacman-key --populate archlinux &&pacman-key --refresh-keys
RUN pacman -Syyu --needed --noconfirm archlinux-keyring && \
    pacman -Syu --needed --noconfirm base-devel ccache distcc git gcc make cmake boost boost-libs sqlite libevent bzip2 zlib curl readline pam valgrind vim qt5-base qt5-declarative qt5-tools libunwind && rm -rf /var/cache/* /tmp/* && \
    pacman-db-upgrade
